### ISSUE TITLE
 Fatal Error: 'Call to a member function ex() on integer' in /var/www/html/setup.php:164 #0 {main}

### ISSUE THREAD

**Issue by turboaaa** [breakall/mytinytodo-docker#1]
I am getting the following error when running the setup using sqllite.

```
myTinyTodo 1.4.3 Setup


Fatal Error: 'Call to a member function ex() on integer' in /var/www/html/setup.php:164
#0 {main}
```

**Comment by turboaaa** [comment]
This did not happen the first couple times I ran the container. I did find that updating the packages seemed to fix the problem. Checking on the changes I made to the dockerfile, if they work I will post.

**Comment by turboaaa** [comment]
I'm also getting the following in the docker logs when trying to restart the container.

`httpd (pid 7) already running`

**Comment by turboaaa** [comment]
So it looks to be random. Sometimes I into the missing integer error and others I don't.

**Comment by turboaaa** [comment]
I was wrong. It's not missing an integer, it is receiving an integer where one is not supposed to show up. 
Initially the setup script sets the $db to "0" 

`$db = 0;
`
But then later, after checking the environment, it sets it to the correct value of "Database_Sqlite3"

`$db = new Database_Sqlite3;`

This tells me that, for some reason, sometimes it does not update the value and tries to use "0" as the DB connection method. Obviously this does not work. Since this is pulled directly from mytinitodo this might be a issue to open with them. My limited knowledge of php tells me there is nothing in this container that would cause this.

**Comment by turboaaa** [comment]
Yup. Verified by adding an echo command to setup.php to echo out the value of $db before running the sqlite table creation.

```
myTinyTodo 1.4.3 Setup

0
Fatal Error: 'Call to a member function ex() on integer' in /var/www/html/setup.php:165
#0 {main}
```

**Comment by breakall** [comment]
I also randomly ran into this. I found that when the error did occur, if I reloaded the page, the database setup would complete successfully.

I don't think there is an official github for mytinytodo, and the project page lists the last release as over 5 years ago, so I wouldn't hold out for a release to fix it.

**Comment by turboaaa** [comment]
Looks like a custom error handler would do the trick. Have it set the location header to setup.php and it will take care of the rest. Though you would want to make sure it doesn't run more than once. This is beyond my existing experience.

https://insomanic.me.uk/php-trick-catching-fatal-errors-e-error-with-a-custom-error-handler-cea2262697a2
